version: '3.8'

services:
  apache:
    build: ./php
    container_name: apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./projects:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4.32
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mariadb

volumes:
  db_data:
