FROM ubuntu:22.04

# Install ProFTPD 1.3.6, Perl 5.34.1, etc.
RUN apt-get update && apt-get install -y \
    proftpd=1.3.6-1 \
    perl=5.34.1-5 \
    libgd-dev=2.2.5-5 \
    zlib1g-dev=1.2.11 \
    libexpat1=2.0.1-1

# Configure ProFTPD (example)
COPY proftpd.conf /etc/proftpd/proftpd.conf